packages:
  - .
  - apps/**
  - database
  - database/models
  - database/postgres
  - packages/logger
  - packages/config
  - packages/infra
  - packages/cloudinary

onlyBuiltDependencies:
  - '@prisma/client'
  - prisma
